apiVersion: v1
kind: Pod
metadata:
  name: log-generator
spec:
  containers:
    - name: log-generator
      image: busybox
      command: ["sh", "-c", "while true; do wget -qO- http://sidecar-service; sleep 2; done"]