apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-yaml
data:
  ENVIRONMENT: "production"
  APP_NAME: "user_api"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-yaml-individual-key
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app-headless
  template:
    metadata:
      labels:
        app: ip-app-headless
    spec:
      containers:
      - name: my-ip-app
        image: harshajain/ip_app:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: my-config-yaml
              key: ENVIRONMENT
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: my-config-yaml
              key: APP_NAME