apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-yaml-individual-key
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app-headless
  template:
    metadata:
      labels:
        app: ip-app-headless
    spec:
      containers:
      - name: my-ip-app
        image: harshajain/ip_app:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: PASSWORD
            