apiVersion: apps/v1 
kind: Deployment 
metadata: 
   name: ip-app-deployment
spec: 
   replicas: 2
   selector:
      matchLabels:
         app: ip-app
   template:
      metadata: 
         labels:
            app: ip-app
      spec:
         nodeSelector: 
            env: test
         containers:
           - name: ip-app
             image: harshajain/ip_app:2
             ports:
             - containerPort: 8080