apiVersion: v1
kind: Service
metadata:
    name: my-nodeport
spec:
    type: NodePort
    selector:
       app: ip-app
    ports:
     - name: http
       nodePort: 8090
       port: 30002
       targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment-ping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
      - name: my-ip-app
        image: harshajain/ip_app:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80